### ISSUE TITLE
Renderloop.Register2DDrawingLayerAsync does not response if called from main thread

### ISSUE THREAD

**Issue by JohnMasen** [RolandKoenig/SeeingSharp2#3]
Hi,
I've wrote a simple helper class to integrate SeeingSharp2 into my WPF application. however the render loop never starts. after debugging my code, I found the loop.Register2DDrawingLayerAsync() does not return.
Thanks for your help.

Init code (MainWindow.xaml.cs)
`private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            if (DesignerProperties.GetIsInDesignMode(this))
            {
                return;
            }
            CtrlRender.RenderLoop.PrepareRender += RenderLoop_PrepareRender;
            (DataContext as MainViewModel).D2DRenderHelper.Init(CtrlRender.RenderLoop);
        }`

Class definition

`public class D2DRenderHelper<T> where T:RunContext
    {
        private List<Action<Graphics2D>> drawCommands = new List<Action<Graphics2D>>();
        private object drawSync = new object();
        public async Task Init(RenderLoop loop)
        {
            drawCommands.Clear();
            try
            {
                
                await loop.Register2DDrawingLayerAsync(new Custom2DDrawingLayer(drawInternal));
                Debug.WriteLine("init complete"); // this method was never called
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        private void drawInternal(Graphics2D graphics)
        {
            lock (drawSync)
            {
                foreach (var item in drawCommands)
                {
                    item(graphics);
                }
            }
        }

        public void UpdateCommands(T context)
        {
            
        }
    }`

**Comment by RolandKoenig** [comment]
Hi JohnMasen,
hm... seems like the MainLoop (EngineMainLoop) does not run. Do you boostrap Seeing# correctly? (see [Link to Wiki](https://github.com/RolandKoenig/SeeingSharp2/wiki/Bootstrapping-Seeing%23))

You can check the GraphicsCore.Current.MainLoop.IsRunning flag. This one is set to true if all started correctly.

You can also observe the static event GraphicsCore.InternalCatchedException. If something goes wrong during main loop processing, then this event should be triggered.

What happens in RenderLoop_PrepareRender?
If an exception is thrown there then the view gets deregistered from the MainLoop of Seeing# and other methods are not called until one calls ReigsterRenderLoop on the RenderLoop class again. I just checked the source... seems like I'm still miss some error logging here on such a case

**Comment by JohnMasen** [comment]
I found the bootstrap is missing. Now it works like a charm, thank you Roland!
