### ISSUE TITLE
WinUI Nupackage is referencing out dated WinUI framework, which prevents latest WinUI3 project to be build

### ISSUE THREAD

**Issue by JohnMasen** [RolandKoenig/SeeingSharp2#8]
I found the SeeingSharp2.WinUI is referencing ProjectReunion 0.5, seems it's an out dated library and the build template is blocking project build.

Repro Steps:
1. Create a new WinUI3 project with VS2022(Blank App, Packaged),Target Framework=.NET 6.0 
2. Add nuget package "SeeingSharp2.WinUI" To project
**Expected result:**
Project able to build
**Actual Result:**
Project build fail with error
_"Severity	Code	Description	Project	File	Line	Suppression State
Error		Improper project configuration: WindowsPackageType is set to None, but AppxPackage is set to true.	WinUI3_Test1	C:\Users\qijian\.nuget\packages\microsoft.projectreunion.winui\0.5.0\buildTransitive\Microsoft.Build.Msix.Packaging.targets	122	
"_
_"Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1022	Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'MainWindow.xaml'	WinUI3_Test1	C:\Users\qijian\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.WinUI.targets	60	"_

**Comment by RolandKoenig** [comment]
I updated it in the current codebase.
It seems to work good with current version of the WindowsAppSDK (1.0)

But I'm hanging on this issue here when it comes to build a nuget package:
https://github.com/microsoft/WindowsAppSDK/issues/1652

**Comment by JohnMasen** [comment]
Thanks for your support, Roland.
I'll use the source code before nuget package issue is solved.

**Comment by RolandKoenig** [comment]
Now I finally updated the nuget (--> Version 0.8.1)
The solution was just to build the package using msbuild instead of nuget pack
